// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 *
 */
public class BuildSettlementAction extends Action {
	/**
	 *
	 */
	private Node target;

	public BuildSettlementAction(Node target) {
		this.target = target;
	}

	/**
	 *
	 * @param b
	 * @param a
	 * @return
	 */
	public boolean execute(Board b, Agent a) {
		a.pay(Cost.SETTLEMENT);
		return b.placeSettlement(a, target);
	}

	/**
	 *
	 * @return
	 */
	public String describe() {
		return "Built settlement at node " + target.getId();
	}
}
