// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import java.util.HashMap;
import java.util.Map;

/************************************************************/
/**
 *
 */
public class Cost {
	/**
	 *
	 */
	private Map<ResourceType, Integer> required;

	public static final Cost SETTLEMENT;
	public static final Cost ROAD;
	public static final Cost CITY;

	static {
		SETTLEMENT = new Cost();
		SETTLEMENT.required = new HashMap<>();
		SETTLEMENT.required.put(ResourceType.WOOD, 1);
		SETTLEMENT.required.put(ResourceType.BRICK, 1);
		SETTLEMENT.required.put(ResourceType.SHEEP, 1);
		SETTLEMENT.required.put(ResourceType.WHEAT, 1);

		ROAD = new Cost();
		ROAD.required = new HashMap<>();
		ROAD.required.put(ResourceType.WOOD, 1);
		ROAD.required.put(ResourceType.BRICK, 1);

		CITY = new Cost();
		CITY.required = new HashMap<>();
		CITY.required.put(ResourceType.ORE, 3);
		CITY.required.put(ResourceType.WHEAT, 2);
	}

	public Map<ResourceType, Integer> getRequired() {
		return required;
	}
}
