// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * Demonstrator: entry point for running and showcasing the Catan simulator.
 *
 * Config loading: reads turns from config.txt (default 100).
 * Board setup: 19 hexes, 54 nodes, ~72 edges hard-wired to standard Catan layout.
 * Setup phase: each of the 4 RandomAgents places 2 settlements + 2 roads for free.
 *   Second settlement placement grants starting resources from adjacent hexes.
 * Main game loop: each round, every agent rolls 2d6, collects resources, then
 *   optionally builds a settlement, road, or upgrades a settlement to a city.
 * Win condition: first agent to reach 10 victory points wins.
 * Output format: [RoundNumber] / [PlayerID]: [Action description]
 *   Round summaries show VP totals after each complete round.
 */
public class Demonstrator {
	/**
	 *
	 * @param args
	 */
	public static void main(String[] args) {
		// Config file path — turns: int [1-8192] read from config.txt
		String config = "src/catan/config.txt";

		// --- Full simulation: rounds loaded from config.txt ---
		System.out.println("=== Catan Simulator: Full Run (rounds from config.txt) ===");
		CatanSimulator sim = new CatanSimulator(config);
		sim.runSimulation();

		// --- Short 5-round demo showing key mechanics ---
		// Temporarily write a 5-round config for the demo
		System.out.println();
		System.out.println("=== Catan Simulator: 5-Round Demo ===");
		System.out.println("Key mechanics demonstrated:");
		System.out.println("  * Setup phase: free placements, starting resource grants");
		System.out.println("  * Dice roll -> resource distribution");
		System.out.println("  * Actions: BuildSettlement, BuildRoad, UpgradeToCity");
		System.out.println("  * R1.8: agents with >7 cards MUST attempt to build ([hand limit] tag)");
		System.out.println("  * Win condition: 10 VP ends the game");
		System.out.println();
		// 5-round override for demo purposes (config path still provided for consistency)
		CatanSimulator demo = new CatanSimulator(config, 5);
		demo.runSimulation();
	}
}
