// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 *
 */
public class MoveValidator {
	/**
	 *
	 * @param b
	 * @param a
	 * @param n
	 * @return
	 */
	public boolean canPlaceSettlement(Board b, Agent a, Node n) {
		return b.getAvailableNodesForSettlement(a).contains(n) && a.canAfford(Cost.SETTLEMENT);
	}

	/**
	 *
	 * @param b
	 * @param a
	 * @param e
	 * @return
	 */
	public boolean canPlaceRoad(Board b, Agent a, Edge e) {
		return b.getAvailableEdgesForRoad(a).contains(e) && a.canAfford(Cost.ROAD);
	}

	/**
	 *
	 * @param b
	 * @param a
	 * @param n
	 * @return
	 */
	public boolean canUpgradeToCity(Board b, Agent a, Node n) {
		return b.canUpgradeToCity(a, n) && a.canAfford(Cost.CITY);
	}
}
