// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import java.util.ArrayList;

/************************************************************/
/**
 *
 */
public class Node {
	/**
	 *
	 */
	private int id;
	/**
	 *
	 */
	Agent owner;
	/**
	 *
	 */
	BuildingType building;
	/**
	 *
	 */
	public java.util.List<Edge> edges;

	public Node(int id) {
		this.id = id;
		this.owner = null;
		this.building = BuildingType.NONE;
		this.edges = new ArrayList<>();
	}

	public int getId() { return id; }
	public Agent getOwner() { return owner; }
	public BuildingType getBuilding() { return building; }
}
