// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

import java.util.ArrayList;
import java.util.List;

/************************************************************/
/**
 *
 */
public class RandomAgent extends Agent {
	/**
	 *
	 */
	java.util.Random rng;

	public RandomAgent(int id) {
		initAgent(id);
		rng = new java.util.Random();
	}

	/**
	 *
	 * @param b
	 * @return
	 */
	public Action chooseAction(Board b) {
		List<Action> possible = new ArrayList<>();

		for (Node n : b.getAvailableNodesForSettlement(this)) {
			if (canAfford(Cost.SETTLEMENT)) {
				possible.add(new BuildSettlementAction(n));
			}
		}

		for (Edge e : b.getAvailableEdgesForRoad(this)) {
			if (canAfford(Cost.ROAD)) {
				possible.add(new BuildRoadAction(e));
			}
		}

		for (Node n : b.getNodes().values()) {
			if (b.canUpgradeToCity(this, n) && canAfford(Cost.CITY)) {
				possible.add(new UpgradeToCityAction(n));
			}
		}

		if (possible.isEmpty()) return null;
		return possible.get(rng.nextInt(possible.size()));
	}
}
