// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public abstract class Action extends BuildSettlementAction {
	/**
	 * 
	 * @param a 
	 * @param b 
	 * @return 
	 */
	public boolean execute(Agent a, Board b) {
	}

	/**
	 * 
	 * @return 
	 */
	public String describe() {
	}
}
