// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public abstract class Agent extends RandomAgent {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceHand hand;
	/**
	 * 
	 */
	private int victoryPoints;

	/**
	 * 
	 * @return 
	 */
	public int getId() {
		return 0;
	}

	/**
	 * 
	 * @return 
	 */
	public int getVictoryPoints() {
		return 0;
	}

	/**
	 * 
	 * @param delta 
	 */
	public void addVictoryPoints(int delta) {
	}

	/**
	 * 
	 * @param r 
	 * @param amount 
	 */
	public void addResource(ResourceType r, int amount) {
	}

	/**
	 * 
	 * @param c 
	 * @return 
	 */
	public boolean canAfford(Cost c) {
		return false;
	}

	/**
	 * 
	 * @param c 
	 */
	public void pay(Cost c) {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean checkHandLimit() {
		return false;
	}

	/**
	 * 
	 * @param b 
	 * @return 
	 */
	public Action chooseAction(Board b) {
		return null;
	}
}
