// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	private java.util.Map<Integer, Hex> hexes;
	/**
	 * 
	 */
	private java.util.Map<Integer, Node> nodes;
	/**
	 * 
	 */
	private java.util.Map<Integer, Edge> edges;

	/**
	 * 
	 */
	public void setupMap() {
	}

	/**
	 * 
	 * @param rollValues 
	 */
	public void distributeResources(int rollValues) {
	}

	/**
	 * 
	 * @param a 
	 * @return 
	 */
	public java.util.List<Node> getAvailableNodesForSettlement(Agent a) {
		return null;
	}

	/**
	 * 
	 * @param a 
	 * @return 
	 */
	public java.util.List<Edge> getAvailableEdgesForRoad(Agent a) {
		return null;
	}

	/**
	 * 
	 * @param a 
	 * @param n 
	 * @return 
	 */
	public boolean canUpgradeToCity(Agent a, Node n) {
		return false;
	}

	/**
	 * 
	 * @param a 
	 * @param n 
	 * @return 
	 */
	public boolean placeSettlement(Agent a, Node n) {
			return false;
	}

	/**
	 * 
	 * @param a 
	 * @param n 
	 * @return 
	 */
	public boolean placeRoad(Agent a, Node n) {
		return false;
	}

	/**
	 * 
	 * @param a 
	 * @param n 
	 * @return 
	 */
	public boolean upgradeToCity(Agent a, Node n) {
		return false;
	}
}
