// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class CatanSimulator {
	/**
	 * 
	 */
	public class Class1 {
	};

	/**
	 * 
	 */
	private int currentRound;
	/**
	 * 
	 */
	private int maxRounds;
	/**
	 * 
	 */
	private Board board;
	/**
	 * 
	 */
	private Dice dice;
	/**
	 * 
	 */
	private java.util.List<Agent>[] agents;
	/**
	 * 
	 */
	public Agent[] agent;
	/**
	 * 
	 */
	private MoveValidator rules;

	/**
	 * 
	 */
	public void runSimulation() {
	}

	/**
	 * 
	 * @param a 
	 */
	private void runTurn(Agent a) {
	}

	/**
	 * 
	 * @return 
	 */
	private boolean checkWinCondition() {
	}

	/**
	 * 
	 */
	private void printRoundSummary() {
	}

	/**
	 * 
	 * @param round 
	 * @param playerId 
	 * @param action 
	 */
	private void logAction(int round, int playerId, String action) {
	}
}
