// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Cost {
	/**
	 * 
	 */
	private java.util.Map<ResourceType, Integer> required;
}
