// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Dice {
	/**
	 * 
	 */
	private java.util.Random rng;

	/**
	 * 
	 * @return 
	 */
	public int roll() {
	}
}
