// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Agent owner;
	/**
	 * 
	 */
	private Node a;
	/**
	 * 
	 */
	private Node b;
}
