// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Hex {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private TerrainType terrain;
	/**
	 * 
	 */
	private int numberToken;
	/**
	 * 
	 */
	private java.util.List<Node> corners;
	/**
	 * 
	 */
	public Node[] node;
}
