// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class MoveValidator {
	/**
	 * 
	 * @param b 
	 * @param a 
	 * @param n 
	 * @return 
	 */
	public boolean canPlaceSettlement(Board b, Agent a, Node n) {
	}

	/**
	 * 
	 * @param b 
	 * @param a 
	 * @param e 
	 * @return 
	 */
	public boolean canPlaceRoad(Board b, Agent a, Edge e) {
	}

	/**
	 * 
	 * @param b 
	 * @param a 
	 * @param n 
	 * @return 
	 */
	public boolean canUpgradeToCity(Board b, Agent a, Node n) {
	}
}
