// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Agent owner;
	/**
	 * 
	 */
	private BuildingType building;
	/**
	 * 
	 */
	public java.util.List<Edge> edges;
}
