// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class RandomAgent {
	/**
	 * 
	 */
	java.util.Random rng;

	/**
	 * 
	 * @param b 
	 * @return 
	 */
	public Action chooseAction(Board b) {
		return null;
	}
}
