// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * 
 */
public class ResourceHand {
	/**
	 * 
	 */
	private java.util.Map<ResourceType, Integer> counts;

	/**
	 * 
	 * @return 
	 */
	public int getTotalCards() {
	}

	/**
	 * 
	 * @param r 
	 * @param amount 
	 */
	public void add(ResourceType r, int amount) {
	}

	/**
	 * 
	 * @param r 
	 * @param amount 
	 */
	public void remove(ResourceType r, int amount) {
	}

	/**
	 * 
	 * @param r 
	 * @return 
	 */
	public int get(ResourceType r) {
	}
}
