// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 *
 */
public class BuildRoadAction extends Action {
	/**
	 *
	 */
	private Edge target;

	public BuildRoadAction(Edge target) {
		this.target = target;
	}

	/**
	 *
	 * @param b
	 * @param a
	 * @return
	 */
	public boolean execute(Board b, Agent a) {
		a.pay(Cost.ROAD);
		return b.placeRoad(a, target);
	}

	/**
	 *
	 * @return
	 */
	public String describe() {
		return "Built road at edge " + target.getId();
	}
}
