// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 * Demonstrator: entry point for running and showcasing the Catan simulator.
 *
 * Config loading: reads turns from config.txt (default 100).
 * Board setup: 19 hexes, 54 nodes, ~72 edges hard-wired to standard Catan layout.
 * Setup phase: each of the 4 RandomAgents places 2 settlements + 2 roads for free.
 *   Second settlement placement grants starting resources from adjacent hexes.
 * Main game loop: each round, every agent rolls 2d6, collects resources, then
 *   optionally builds a settlement, road, or upgrades a settlement to a city.
 * Win condition: first agent to reach 10 victory points wins.
 * Output format: [RoundNumber] / [PlayerID]: [Action description]
 *   Round summaries show VP totals after each complete round.
 */
public class Demonstrator {
	/**
	 *
	 * @param args
	 */
	public static void main(String[] args) {
		// --- Full simulation (up to 100 rounds from config) ---
		System.out.println("=== Catan Simulator: Full Run (max 100 rounds) ===");
		CatanSimulator sim = new CatanSimulator(100);
		sim.runSimulation();

		// --- Short 5-round demo showing key mechanics ---
		System.out.println();
		System.out.println("=== Catan Simulator: 5-Round Demo ===");
		System.out.println("Key mechanics demonstrated:");
		System.out.println("  * Setup phase: free placements, starting resource grants");
		System.out.println("  * Dice roll -> resource distribution");
		System.out.println("  * Actions: BuildSettlement, BuildRoad, UpgradeToCity");
		System.out.println("  * Win condition: 10 VP ends the game");
		System.out.println();
		CatanSimulator demo = new CatanSimulator(5);
		demo.runSimulation();
	}
}
