// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 *
 */
public class Dice {
	/**
	 *
	 */
	private java.util.Random rng;

	public Dice() {
		rng = new java.util.Random();
	}

	/**
	 *
	 * @return
	 */
	public int roll2d6() {
		return rng.nextInt(6) + 1 + rng.nextInt(6) + 1;
	}
}
