// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package catan;

/************************************************************/
/**
 *
 */
public class UpgradeToCityAction extends Action {
	/**
	 *
	 */
	private Node target;

	public UpgradeToCityAction(Node target) {
		this.target = target;
	}

	/**
	 *
	 * @param b
	 * @param a
	 * @return
	 */
	public boolean execute(Board b, Agent a) {
		a.pay(Cost.CITY);
		return b.upgradeToCity(a, target);
	}

	/**
	 *
	 * @return
	 */
	public String describe() {
		return "Upgraded to city at node " + target.getId();
	}
}
